### ISSUE TITLE
Application of translation

### ISSUE THREAD

**Issue by hellosoftcoding** [AppyBuilder/AppyBuilder-Source#31]
I modified the Korean translation file 'OdeMessages_ko_KR.properties' 
two days ago and made a pull request.

My pull has been approved and the changes have been applied.

However, this translated Korean is not currently displayed on the website.
I ask for help.

Thank you.

**Comment by Amerkashi** [comment]
Hi, It has been merged, but not released yet. Will be released to offline soon.

**Comment by hellosoftcoding** [comment]
Oh, I got it! Thanks!
